version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
    env_file:
      - ./.env
    ports:
      - "3001:3001"

  app:
    build:
      context: ./app
    env_file:
      - ./.env
    ports:
      - "3002:3002"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - admin
      - app