FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# Устанавливаем bash
RUN apk add --no-cache bash

COPY . .
COPY scripts/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start:dev"]
EXPOSE 9000