server {
    listen 80;
    server_name localhost;
    
    # Админка
    location /admin {
        proxy_pass http://admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        rewrite ^/admin(/.*)$ $1 break;
    }
    
    # Основное приложение
    location /app {
        proxy_pass http://app/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        rewrite ^/app(/.*)$ $1 break;
    }
    
    # API
    location /api {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Перенаправление с корня на /app
    location / {
        return 301 /app;
    }
}