events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;
        
        location /admin {
            proxy_pass http://admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/admin(/.*)$ $1 break;
        }
        
        location /app {
            proxy_pass http://app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite ^/app(/.*)$ $1 break;
        }
        
        # API
        location /api {
            proxy_pass http://backend:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location / {
            return 301 /app;
        }
    }
}
